#import "../../graphql-fragments/user-fields.gql"
#import "../../graphql-fragments/gamer-tag-fields.gql"
#import ".../../graphql-fragments/profile-snapshot-statistic.gql"

query getCurrentUserQuery {
  me {
    ...UserFields
    followedGamerTags {
      ...GamerTagFields
      snapshotStatistics(last: 1) {
        id
        gamerTagId
        ...ProfileStatistic
      }
    }
    following {
      ...UserFields
      gamerTags {
        ...GamerTagFields
        snapshotStatistics(last: 1) {
          id
          gamerTagId
          ...ProfileStatistic
        }
      }
    }
  }
}