FROM ubuntu:16.10

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV MIX_ENV dev

RUN \
  apt-get update && \
  apt-get install -y wget curl

RUN \
  locale-gen en_US.UTF-8 && \
  update-locale LANG=en_US.UTF-8 && \
  ln -sfn /usr/share/zoneinfo/America/Vancouver /etc/localtime

RUN \
  wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && \
  dpkg -i erlang-solutions_1.0_all.deb && \
  apt-get update && \
  apt-get install -y esl-erlang elixir build-essential openssh-server git postgresql phantomjs

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH $HOME/.cargo/bin:$PATH

RUN mix local.hex --force
RUN mix local.rebar --force

COPY ./server /home/server
RUN cd /home/server && mix deps.get
RUN cd /home/server && PATH=$HOME/.cargo/bin:$PATH mix compile
RUN su - postgres -c '/usr/lib/postgresql/9.5/bin/initdb -D ~/db'
RUN su - postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl -D ~/db start' && \
    cd /home/server && \
    mix do ecto.create, ecto.migrate

ENTRYPOINT [ \
  "sh", \
  "-c", \
  "su - postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl -D ~/db start' && sleep 60 && cd /home/server && phantomjs -w --load-images=false & PATH=$HOME/.cargo/bin:$PATH mix phx.server" \
]
EXPOSE 4000
