#import "./blog-category-fields.gql"
#import "./author-fields.gql"
#import "./blog-post-fields.gql"

query BlogPostsAfter($first: Int!, $after: Int!) {
    blogPosts(first: $first, after: $after) {
      ...BlogPostFields
      author {
        ...AuthorFields
      }
      blogCategories {
        ...BlogCategoryFields
      }
    }
  }