#import "./blog-category-fields.gql"
#import "./author-fields.gql"
#import "./blog-post-fields.gql"

query BlogPosts($last: Int!, $before: Int!, $first: Int!, $after: Int!) {
  blogPosts(last: $last, before: $before, first: $first, after: $after) {
    ...BlogPostFields
    author {
      ...AuthorFields
    }
    blogCategories {
      ...BlogCategoryFields
    }
  }
}
