#import "./gamer-tag-fields.gql"
#import "./profile-snapshot-statistic.gql"
#import "./hero-snapshot-fields"
#import "./heroes-total-snapshot-statistic.gql"

query FetchGamerTag($id: Int, $tag: String, $region: String, $platform: String, $snapshotLast: Int) {
    gamerTag(id: $id, tag: $tag, region: $region, platform: $platform) {
      ...GamerTagFields
      snapshotStatistics(last: $snapshotLast) {
        id
        gamerTagId
        insertedAt
        ...ProfileStatistic
        quickplayHeroSnapshotStatistics: heroSnapshotStatistics(type: QUICKPLAY) {
          ...HeroSnapshotStatistics
        }
        competitiveHeroSnapshotStatistics: heroSnapshotStatistics(type: COMPETITIVE) {
          ...HeroSnapshotStatistics
        }
        quickplayHeroesTotalSnapshotStatistic: heroesTotalSnapshotStatistic(type: QUICKPLAY) {
          ...HeroesTotalSnapShot
        }
        competitiveHeroesTotalSnapshotStatistic: heroesTotalSnapshotStatistic(type: COMPETITIVE) {
          ...HeroesTotalSnapShot
        }
      }
      connectedGamerTags {
        ...GamerTagFields
        snapshotStatistics(last: $snapshotLast) {
          id
          gamerTagId
          insertedAt
          ...ProfileStatistic
          quickplayHeroSnapshotStatistics: heroSnapshotStatistics(type: QUICKPLAY) {
            ...HeroSnapshotStatistics
          }
          competitiveHeroSnapshotStatistics: heroSnapshotStatistics(type: COMPETITIVE) {
            ...HeroSnapshotStatistics
          }
          quickplayHeroesTotalSnapshotStatistic: heroesTotalSnapshotStatistic(type: QUICKPLAY) {
            ...HeroesTotalSnapShot
          }
          competitiveHeroesTotalSnapshotStatistic: heroesTotalSnapshotStatistic(type: COMPETITIVE) {
            ...HeroesTotalSnapShot
          }
        }
      }
    }
  }