#import "./hero-snapshot-fields"
#import "./heroes-total-snapshot-statistic.gql"
#import "./profile-snapshot-statistic.gql"

query FetchSnapshot($snapshotLast: Int, $type: SnapshotStatisticType!) {
  snapshotStatistics(last: $snapshotLast) {
      id
      insertedAt
      ...ProfileStatistic
      heroSnapshotStatistics(type: $type) {
        ...HeroSnapshotStatistics
      }
      heroesTotalSnapshotStatistic(type: $type) {
        ...HeroesTotalSnapShot
      }
    }
}