#import "../statistics/match-award-statistic-field.gql"
#import "../statistics/game-history-statistic.gql"
#import "../statistics/combat-best-statistic.gql"
#import "../statistics/combat-life-statistic.gql"

fragment HeroesTotalSnapShot on HeroesTotalSnapshotStatistic {
  id
  statisticType
  gameHistoryStatisticId
  matchAwardsStatistic {
    id
    ...MatchAwardStatistic
  }
  gameHistoryStatistic {
    id
    ...GameHistoryStatistic
  }
  combatLifetimeStatistic {
    id
    ...CombatLifeStatistic
  }
  combatBestStatistic {
    id
    ...CombatBestStatistic
  }
}