query SkillRatingTrend($id: Int) {
  gamerTag(id: $id) {
    id
    snapshotStatistics(last: 7) {
      id
      insertedAt
      profileSnapshotStatistic {
        id
        profileStatistic {
          competitiveLevel
        }
      }
    }
  }
}