#import "../gamertag/gamer-tag-fields.gql"
#import "../gamertag/profile-snapshot-statistic.gql"

fragment FriendshipFields on Friendship {
  id
  friendId
  isAccepted
  insertedAt
  updatedAt
  primaryGamerTagId
  primaryGamerTag {
    ...GamerTagFields
    snapshotStatistics(last: 1) {
      id
      gamerTagId
      ...ProfileStatistic
    }
  }
}