#import "./friend-ship-fields.gql"
#import "../user/user-fields.gql"
#import "../gamertag/gamer-tag-fields.gql"
#import "../gamertag/profile-snapshot-statistic.gql"
#import "../friend-ship/friend-ship-fields.gql"

query PendingFriendShipsQuery {
  me {
    id
    incomingRequests: friendships(isIncoming: true, isAccepted: false) {
      ...FriendshipFields
      friend {
        ...UserFields
        gamerTags {
          ...GamerTagFields
          snapshotStatistics(last: 1) {
            id
            gamerTagId
            ...ProfileStatistic
          }
        }
      }
    }
    outgoingRequests: friendships(isIncoming: false, isAccepted: false) {
      ...FriendshipFields
      friend {
        ...UserFields
        gamerTags {
          ...GamerTagFields
          snapshotStatistics(last: 1) {
            id
            gamerTagId
            ...ProfileStatistic
          }
        }
      }
    }
  }
}