import gql from 'graphql-tag';

export const gamerTagSearchQuery = gql`
  query GamerTagSearch($tag: String!) {
    searchGamerTag(tag: $tag) {
      id
      updatedAt
      totalGamesWon
      tag
      snapshotStatistics {
        id
        isCompetitive
        gamerTagId
        heroSnapshotStatistics {
          id
          heroSpecificStatistic {
            id
            stats
          }
          matchAwardsStatistic {
            id
            totalMedals
            goldMedals
            silverMedals
            bronzeMedals
            cards
          }
          heroId
          hero {
            id
            code
            name
            insertedAt
            updatedAt
          }
          gameHistoryStatisticId
          gameHistoryStatistic {
            id
            winPercentage
            timeSpentOnFire
            timePlayed
            gamesWon
            gamesPlayed
            gamesLost
          }
          combatLifetimeStatistic {
            id
            weaponAccuracyPercentage
            turretsDestroyed
            timeSpentOnFire
            teleporterPadsDestroyed
            soloKills
            shotsHit
            shotsFired
            reconAssists
            offensiveAssists
            objectiveTime
            objectiveKills
            multikills
            multikillBest
            meleeKills
            meleeFinalBlows
            healingDone
            finalBlows
            environmentalKills
            environmentalDeaths
            eliminationsPerLife
            eliminations
            defensiveAssists
            deaths
            damageDone
            damageBlocked
            criticalHitsAccuracyPercentage
            criticalHits
          }
          combatBestStatistic {
            id
            weaponAccuracyBestInGamePercentage
            timeSpentOnFireMostInGame
            soloKillsMostInGame
            selfHealingMostInGame
            reconAssistsMostInGame
            offensiveAssistsMostInGame
            objectiveTimeMostInGame
            objectiveKillsMostInGame
            multikillBest
            meleeKillsMostInGame
            meleeFinalBlowsMostInGame
            killStreakBest
            healingDoneMostInLife
            healingDoneMostInGame
            finalBlowsMostInGame
            eliminationsMostInLife
            eliminationsMostInGame
            defensiveAssistsMostInGame
            damageDoneMostInLife
            damageDoneMostInGame
            damageBlockedMostInGame
            criticalHitsMostInLife
            criticalHitsMostInGame
          }
          combatAverageStatistic {
            id
            timeSpentOnFireAverage
            soloKillsAverage
            selfHealingAverage
            offensiveAssistsAverage
            objectiveTimeAverage
            objectiveKillsAverage
            meleeKillsAverage
            meleeFinalBlowsAverage
            healingDoneAverage
            finalBlowsAverage
            eliminationsAverage
            defensiveAssistsAverage
            deathsAverage
            damageDoneAverage
            damageBlockedAverage
          }
        }
        allHeroesSnapshotStatistic {
          matchAwardsStatistic {
            id
            totalMedals
            goldMedals
            silverMedals
            bronzeMedals
            cards
          }
          gameHistoryStatisticId
          gameHistoryStatistic {
            id
            winPercentage
            timeSpentOnFire
            timePlayed
            gamesWon
            gamesPlayed
            gamesLost
          }
          combatLifetimeStatistic {
            id
            weaponAccuracyPercentage
            turretsDestroyed
            timeSpentOnFire
            teleporterPadsDestroyed
            soloKills
            shotsHit
            shotsFired
            reconAssists
            offensiveAssists
            objectiveTime
            objectiveKills
            multikills
            multikillBest
            meleeKills
            meleeFinalBlows
            healingDone
            finalBlows
            environmentalKills
            environmentalDeaths
            eliminationsPerLife
            eliminations
            defensiveAssists
            deaths
            damageDone
            damageBlocked
            criticalHitsAccuracyPercentage
            criticalHits
          }
          combatBestStatistic {
            id
            weaponAccuracyBestInGamePercentage
            timeSpentOnFireMostInGame
            soloKillsMostInGame
            selfHealingMostInGame
            reconAssistsMostInGame
            offensiveAssistsMostInGame
            objectiveTimeMostInGame
            objectiveKillsMostInGame
            multikillBest
            meleeKillsMostInGame
            meleeFinalBlowsMostInGame
            killStreakBest
            healingDoneMostInLife
            healingDoneMostInGame
            finalBlowsMostInGame
            eliminationsMostInLife
            eliminationsMostInGame
            defensiveAssistsMostInGame
            damageDoneMostInLife
            damageDoneMostInGame
            damageBlockedMostInGame
            criticalHitsMostInLife
            criticalHitsMostInGame
          }
          combatAverageStatistic {
            id
            timeSpentOnFireAverage
            soloKillsAverage
            selfHealingAverage
            offensiveAssistsAverage
            objectiveTimeAverage
            objectiveKillsAverage
            meleeKillsAverage
            meleeFinalBlowsAverage
            healingDoneAverage
            finalBlowsAverage
            eliminationsAverage
            defensiveAssistsAverage
            deathsAverage
            damageDoneAverage
            damageBlockedAverage
          }
        }
      }
      region
      portraitUrl
      platform
      overwatchName
      levelUrl
      level
      insertedAt
      competitiveRankUrl
      competitiveLevel
    }
  }
`;
