fragment CombatLifeStatistic on CombatLifetimeStatistic {
  weaponAccuracyPercentage
  turretsDestroyed
  timeSpentOnFire
  teleporterPadsDestroyed
  soloKills
  reconAssists
  offensiveAssists
  objectiveTime
  objectiveKills
  multikills
  meleeKills
  meleeFinalBlows
  healingDone
  finalBlows
  environmentalKills
  eliminationsPerLife
  eliminations
  defensiveAssists
  deaths
  damageBlocked
  criticalHitsAccuracyPercentage
  criticalHits
}