fragment GameAverageStatisticAverage on GameAverageStatisticAverage {
  allDamageDoneAvgPer10Min
  barrierDamageDoneAvgPer10Min
  criticalHitsAvgPer10Min
  damageBlockedAvgPer10Min
  deathsAvgPer10Min
  defensiveAssistsAvgPer10Min
  eliminationsAvgPer10Min
  finalBlowsAvgPer10Min
  healingDoneAvgPer10Min
  heroDamageDoneAvgPer10Min
  meleeFinalBlowsAvgPer10Min
  objectiveKillsAvgPer10Min
  objectiveTimeAvgPer10Min
  offensiveAssistsAvgPer10Min
  selfHealingAvgPer10Min
  soloKillsAvgPer10Min
  timeSpentOnFireAvgPer10Min
}