#import "../hero/hero-fields.gql"
#import "./match-award-statistic-average.gql"
#import "./game-history-statistic-average.gql"
#import "./combat-life-statistic-average.gql"
#import "./combat-best-statistic-average.gql"
#import "./game-average-statistic-average.gql"

query HeroStatisticsAverageSearch($heroId: Int!) {
    competitiveHeroAverages: heroStatisticsAverage(heroId: $heroId, type: COMPETITIVE) {
      matchAwardsStatistic {
        ...MatchAwardStatistic
      }
      hero {
        ...HeroFields
      }
      gameHistoryStatistic {
        ...GameHistoryStatistic
      }
      combatLifetimeStatistic {
        ...CombatLifeStatistic
      }
      combatBestStatistic {
        ...CombatBestStatistic
      }
      gameAverageStatistic {
        ...GameAverageStatistic
      }
    }
    quickplayHeroAverages :heroStatisticsAverage(heroId: $heroId, type:  QUICKPLAY) {
      matchAwardsStatistic {
        ...MatchAwardStatistic
      }
      hero {
        ...HeroFields
      }
      gameHistoryStatistic {
        ...GameHistoryStatistic
      }
      combatLifetimeStatistic {
        ...CombatLifeStatistic
      }
      combatBestStatistic {
        ...CombatBestStatistic
      }
      gameAverageStatistic {
        ...GameAverageStatistic
      }
    }
  }
