#import "../hero/hero-fields.gql"
#import "./match-award-statistic-average.gql"
#import "./game-history-statistic-average.gql"
#import "./combat-life-statistic-average.gql"
#import "./combat-best-statistic-average.gql"
#import "./game-average-statistic-average.gql"

query HeroStatisticsAverageSearch($heroId: Int!, $platform: String, $region: String, $type: SnapshotStatisticType!) {
    heroStatisticsAggregateAverage(heroId: $heroId, region: $region, platform: $platform, type: $type) {
      matchAwardsStatistic {
        ...MatchAwardsStatisticAverage
      }
      hero {
        ...HeroFields
      }
      gameHistoryStatistic {
        ...GameHistoryStatisticAverage
      }
      combatLifetimeStatistic {
        ...CombatLifetimeStatisticAverage
      }
      combatBestStatistic {
        ...CombatBestStatisticAverage
      }
      gameAverageStatistic {
        ...GameAverageStatisticAverage
      }
    }
  }
