#import "../hero/hero-fields.gql"
#import "./match-award-statistic-field.gql"
#import "./game-history-statistic.gql"
#import "./combat-life-statistic.gql"
#import "./combat-best-statistic.gql"

query SnapshotStatsAverageSearch($type: SnapshotStatisticType!) {
    snapshotsStatisticsAggregateAverage(type: $type) {
      heroSnapshotStatistics {
        matchAwardsStatistic {
          ...MatchAwardStatistic
        }
        hero {
          ...HeroFields
        }
        gameHistoryStatistic {
          ...GameHistoryStatistic
        }
        combatLifetimeStatistic {
          ...CombatLifeStatistic
        }
        combatBestStatistic {
          ...CombatBestStatistic
        }
      }
      heroesTotalSnapshotStatistic {
        matchAwardsStatistic {
          ...MatchAwardStatistic
        }
        gameHistoryStatistic {
          ...GameHistoryStatistic
        }
        combatLifetimeStatistic {
          ...CombatLifeStatistic
        }
        combatBestStatistic {
          ...CombatBestStatistic
        }
      }
    }
  }
