#import "./user-fields.gql"

mutation CreateUser($password: String!, $displayName: String!, $email: String!, $clientAuthToken: String!) {
  createUser(password: $password, displayName: $displayName, email: $email, clientAuthToken: $clientAuthToken) {
    ...UserFields
  }
}
