#import "../gamertag/gamer-tag-fields.gql"
#import "../gamertag/profile-snapshot-statistic.gql"

fragment UserFields on User {
  id
  battleNetId
  battleNetTag
  displayName
  email
  insertedAt
  updatedAt
  primaryGamerTagId
  primaryGamerTag {
    ...GamerTagFields
    snapshotStatistics(last: 1) {
      id
      gamerTagId
      ...ProfileStatistic
    }
  }
}