fragment HeroFields on Hero {
  id
  description
  iconPortraitUrl
  name
  role {
    id
    name
    svgUrl
  }
  selectPortraitUrl
  skills {
    description
    iconUrl
    id
    name
  }
  insertedAt
  updatedAt
}