import { ModuleWithProviders, NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { HttpModule } from '@angular/http';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { SharedModule } from '../shared/shared.module';
import { ChartsModule } from '../charts';
import { InfiniteScrollModule } from 'ngx-infinite-scroll';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MomentModule } from 'angular2-moment';
import { RouterModule } from '@angular/router';

import { PipeModule } from '../pipes';

import { QuillModule } from 'ngx-quill';

import { TagInputModule } from 'ng2-tag-input';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgxChartsModule } from '@swimlane/ngx-charts';

import {
  MdInputModule,
  MdButtonModule,
  MdCardModule,
  MdSnackBarModule,
  MdTabsModule,
  MdIconModule,
  MdListModule,
  MdSelectModule,
  MdProgressSpinnerModule,
  MdChipsModule,
  MdSlideToggleModule,
  MdTooltipModule,
  MdToolbarModule,
  MdTableModule,
  MdRadioModule,
  MdButtonToggleModule,
  MdCheckboxModule,
  MdProgressBarModule,
  MdExpansionModule,
  MdGridListModule
} from '@angular/material';

import {
  HomeComponent,
  FollowingComponent,
  FollowedUserComponent,
  GamerTagCardComponent,
  LeaderboardComponent,
  HeroesComponent,
  HeroComponent,
  HeroHeaderComponent,
  ESportsComponent,
  LiveComponent,
  NewsComponent,
  PostComponent,
  FriendsComponent,
  ProfileComponent,
  LifetimeStatsComponent,
  ProfileCareerComponent,
  MostPlayedComponent,
  HeroSkillsComponent,
  HeroTrendsComponent,
  HeroOverviewComponent,
  HeroSynergiesComponent,
  HeroCountersComponent,
  ProfileOverviewComponent,
  HeroWallCatalogComponent,
  CompareComponent,
  ComparedProfilesComponent,
  StatCategoryBlockComponent,
  HeroesTableComponent,
  PageNotFoundComponent,
  LoginComponent,
  NewsPageFiltersComponent,
  PostEntryComponent,
  UserRegistrationComponent,
  AccountSettingsComponent,
  ListOfCompareableHeroesComponent,
  LeaderboardTableComponent,
  LeaderboardChartComponent,
  HeroesChartComponent,
  RecentlyPlayedComponent,
  OverallPerformanceComponent,
  RolePerformanceComponent,
  RecentSessionComponent,
  SnapshotsHistoryComponent,
  MatchSnapshotComponent,
  MatchDetailsComponent,
  ProfileHeroesComponent,
  ProfileHeroesTableComponent,
  CreatePostComponent,
  CreatePostFormComponent,
  TrendsComponent,
  SkillRatingTrendComponent,
  SelectorComponent
} from './index';

@NgModule({
  imports: [
    QuillModule,
    RouterModule,
    SharedModule.forRoot(),
    PipeModule.forRoot(),
    ChartsModule.forRoot(),
    FormsModule,
    ReactiveFormsModule,
    BrowserModule,
    CommonModule,
    HttpModule,
    NgxDatatableModule,
    InfiniteScrollModule,
    FlexLayoutModule,
    TagInputModule,
    BrowserAnimationsModule,
    MdInputModule,
    MdButtonModule,
    MdCardModule,
    MdSnackBarModule,
    MdTabsModule,
    MdIconModule,
    MdListModule,
    MdSelectModule,
    MdProgressSpinnerModule,
    MomentModule,
    MdChipsModule,
    MdSlideToggleModule,
    MdTooltipModule,
    MdToolbarModule,
    MdTableModule,
    MdRadioModule,
    MdButtonToggleModule,
    MdCheckboxModule,
    MdProgressBarModule,
    MdExpansionModule,
    MdGridListModule,
    NgxChartsModule
  ],
  declarations: [
    HomeComponent,
    SelectorComponent,
    FollowingComponent,
    FollowedUserComponent,
    GamerTagCardComponent,
    LeaderboardComponent,
    HeroesComponent,
    HeroComponent,
    HeroHeaderComponent,
    CreatePostComponent,
    CreatePostFormComponent,
    ESportsComponent,
    LiveComponent,
    NewsComponent,
    PostComponent,
    FriendsComponent,
    ProfileComponent,
    LifetimeStatsComponent,
    ProfileCareerComponent,
    MostPlayedComponent,
    HeroSkillsComponent,
    HeroTrendsComponent,
    HeroOverviewComponent,
    HeroSynergiesComponent,
    HeroCountersComponent,
    ProfileOverviewComponent,
    HeroWallCatalogComponent,
    CompareComponent,
    ComparedProfilesComponent,
    StatCategoryBlockComponent,
    HeroesTableComponent,
    PageNotFoundComponent,
    LoginComponent,
    NewsPageFiltersComponent,
    PostEntryComponent,
    UserRegistrationComponent,
    AccountSettingsComponent,
    ListOfCompareableHeroesComponent,
    LeaderboardTableComponent,
    LeaderboardChartComponent,
    HeroesChartComponent,
    RecentlyPlayedComponent,
    OverallPerformanceComponent,
    RolePerformanceComponent,
    RecentSessionComponent,
    SnapshotsHistoryComponent,
    MatchSnapshotComponent,
    MatchDetailsComponent,
    ProfileHeroesComponent,
    ProfileHeroesTableComponent,
    TrendsComponent,
    SkillRatingTrendComponent
  ],
  exports: [
    HomeComponent,
    FollowingComponent,
    FollowedUserComponent,
    GamerTagCardComponent,
    LeaderboardComponent,
    HeroesComponent,
    HeroComponent,
    HeroHeaderComponent,
    ESportsComponent,
    LiveComponent,
    NewsComponent,
    PostComponent,
    FriendsComponent,
    ProfileComponent,
    LifetimeStatsComponent,
    ProfileCareerComponent,
    MostPlayedComponent,
    HeroSkillsComponent,
    HeroTrendsComponent,
    HeroOverviewComponent,
    HeroSynergiesComponent,
    HeroCountersComponent,
    LoginComponent,
    UserRegistrationComponent,
    AccountSettingsComponent,
    LeaderboardTableComponent,
    LeaderboardChartComponent,
    HeroesChartComponent,
    OverallPerformanceComponent,
    RolePerformanceComponent,
    RecentSessionComponent,
    SnapshotsHistoryComponent,
    MatchSnapshotComponent,
    MatchDetailsComponent,
    ProfileHeroesComponent,
    ProfileHeroesTableComponent,
    SkillRatingTrendComponent
  ]
})

export class PagesModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: PagesModule
    };
  }
}
